print("Welcome to the tip calculator")
billTotal = input("What was the total bill? RM")
percent = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
nPeople = int(input("How many people to split? "))
new_billTotal = float(billTotal)
pay = round(((new_billTotal+ (new_billTotal * (percent / 100))) / nPeople), 2)
print(f"Each person should pay: RM{pay}" )
